[project]
name = "tesis-wrf-pgich"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "metpy>=1.7.1",
    "netcdf4>=1.7.4",
    "numpy>=2.4.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "scipy>=1.17.1",
    "streamlit>=1.56.0",
    "xarray>=2026.2.0",
    "fastapi>=0.110.0",
    "uvicorn>=0.23.0",
    "pydeck>=0.9.0",
    "pydantic>=2.7.0",
]
